# Generated by Django 5.1.7 on 2025-04-05 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_сomplaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сomplaint',
            new_name='Complaint',
        ),
    ]
