# Generated by Django 5.1.7 on 2025-04-05 08:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='pure_owners_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Нормализованный номер телефона владельца'),
        ),
    ]
