# Generated by Django 5.1.7 on 2025-04-05 08:37

from django.db import migrations
import phonenumbers

def add_valid_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            pure_phone = f'+7{phonenumbers.parse(flat.owners_phonenumber, 'ru').national_number}'
            valid_number = phonenumbers.parse(pure_phone, 'ru')
            if phonenumbers.is_valid_number(valid_number):
                flat.pure_owners_phonenumber = valid_number
                flat.save()
        except phonenumbers.NumberParseException as e:
            pass
    
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_pure_owners_phonenumber'),
    ]

    operations = [
        migrations.RunPython(add_valid_phonenumbers),
    ]
